# Generated by Django 3.2.24 on 2024-03-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('author_id', models.CharField(max_length=20)),
                ('fans_count', models.IntegerField()),
                ('index_source', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('like_count', models.IntegerField()),
                ('video_count', models.IntegerField()),
                ('create_time', models.IntegerField()),
                ('update_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('create_time', models.IntegerField()),
                ('update_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('like_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('share_num', models.IntegerField()),
                ('collect_num', models.IntegerField()),
                ('video_id', models.CharField(max_length=255)),
                ('publish_time', models.CharField(max_length=255)),
                ('create_time', models.IntegerField()),
                ('update_time', models.IntegerField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.creator')),
            ],
        ),
        migrations.AddField(
            model_name='creator',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp.tag'),
        ),
    ]
